# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75, unique=True)),
                ('sigla', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cargaHoraria', models.CharField(choices=[(b'40', b'40 horas'), (b'80', b'80 horas')], default=20, max_length=2)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SistemaHorario.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.IntegerField(default=1234)),
                ('tipoUsuario', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatrizCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPeriodos', models.IntegerField(default=1)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SistemaHorario.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPeriodo', models.IntegerField(default=1)),
                ('disciplina', models.ManyToManyField(to='SistemaHorario.Disciplina')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaHorario.MatrizCurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cargaHoraria', models.CharField(choices=[(b'20', b'20 horas'), (b'40', b'40 horas')], default=20, max_length=2)),
                ('telefone', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('chefe', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaHorario.Departamento')),
                ('disciplina', models.ManyToManyField(to='SistemaHorario.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('semestre', models.CharField(max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaHorario.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SistemaHorario.Professor'),
        ),
    ]
