# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaHorario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrizcurricular',
            name='numeroPeriodos',
        ),
    ]
