# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaHorario', '0003_matrizcurricular_nomematriz'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[(b'Segunda', b'Segunda-feira'), (b'Terca', b'Terca-feira'), (b'Quarta', b'Quarta-feira'), (b'Quinta', b'Quinta-feira'), (b'Sexta', b'Sexta-feira')], default=b'Segunda', max_length=20)),
                ('disciplina', models.ManyToManyField(to='SistemaHorario.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaHorario.Turma')),
            ],
        ),
        migrations.AddField(
            model_name='diasemana',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaHorario.Horario'),
        ),
    ]
