# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaHorario', '0004_auto_20160623_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menssagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=50)),
                ('menssagem', models.CharField(max_length=100)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaHorario.Professor')),
            ],
        ),
    ]
